version: '3.8'

services:
  api:
    container_name: api
    restart: always
    build:
      context: .
      target: dependencies
    networks:
      - postvault_network
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
      # Uncomment the below line if you developing on MacOS
      #- /home/node/app/node_modules
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"
  postgres:
    container_name: postgres
    image: postgres:15.4
    restart: always
    networks:
      - postvault_network
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:

networks:
  postvault_network:
    driver: bridge
